name: Flutter Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.x"

      - name: Get Flutter info
        run: flutter --version

      - name: Install dependencies
        run: |
          cd mexin-flutter-app
          flutter pub get

      - name: Build Debug APK
        run: |
          cd mexin-flutter-app
          flutter build apk --debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: mexin-flutter-app/build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 30
